spring:
    config:
        activate:
            on-profile: study
    datasource:
        url: jdbc:h2:tcp://localhost/~/Desktop/etc/db/test
        username: sa
        password: 1234
        driver-class-name: org.h2.Driver
    jpa:
        database: h2
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            ddl-auto: create-drop
        generate-ddl: true
        show-sql: true


server:
    port: 3040

